title: Inaudible Hunt 
title_var: Inaudible Hunt 
description: A friendly hunt for beginning puzzlers. Starts April 24, 2021 @ noon EDT
  <br>
  <small><b>Interested in learning to write puzzles?</b> Join us by filling out the Contact Us form</small>
show_downloads: false
show_banner: false
google_analytics:
theme: jekyll-theme-leap-day
